# models/constants.py
# Generic fallback bullets used only when AI call fails entirely.
# These are role-agnostic placeholders — real bullets are always generated by AI.

FALLBACK_BULLETS = [
    "Designed and implemented scalable application features using modern frameworks, improving system performance and reliability across production environments",
    "Integrated REST APIs and third-party services to streamline data exchange, reducing manual processing time by over 30% for key business workflows",
    "Collaborated with cross-functional teams including product, design, and QA to deliver high-quality features aligned with business requirements and user needs",
    "Optimized backend services and database queries, achieving significant reductions in response time and supporting increased user traffic at scale",
    "Built and maintained CI/CD pipelines using Git and containerization tools, accelerating deployment frequency and reducing time-to-production for new releases",
    "Implemented authentication, authorization, and security best practices including RBAC and OAuth 2.0, ensuring compliance with enterprise security standards",
    "Developed automated testing suites and monitoring dashboards, improving system observability and reducing mean time to resolution for production incidents",
    "Led technical design discussions and code reviews that elevated team code quality, established reusable patterns, and mentored junior developers",
]
